default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: <%= ENV['TRELLOOO_DEVELOPMENT_DB_NAME'] %>
  username: <%= ENV['TRELLOOO_DEVELOPMENT_DB_USERNAME'] %>
  password: <%= ENV['TRELLOOO_DEVELOPMENT_DB_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['TRELLOOO_TEST_DB_NAME'] %>
  username: <%= ENV['TRELLOOO_TEST_DB_USERNAME'] %>
  password: <%= ENV['TRELLOOO_TEST_DB_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['TRELLOOO_PRODUCTION_DB_NAME'] %>
  username: <%= ENV['TRELLOOO_PRODUCTION_DB_USERNAME'] %>
  password: <%= ENV['TRELLOOO_PRODUCTION_DB_PASSWORD'] %>
  host: <%= ENV['TRELLOOO_PRODUCTION_HOSTNAME'] %>
  port: <%= ENV['TRELLOOO_PRODUCTION_PORT'] %>
